# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e2553742c5d3f0ba634c62c6066a6ad79d3f20be4711619fa5d0231191bd65f03bee657d6aeeb765bd45e1f050b446d6ee2f7fe14e57cda62ba6212393d6fbd

test:
  secret_key_base: 7ac64e2db0e76f05fb98a1733a5577be118b105b52c0c7091e9a700e7fe68dd75dd5c5017ec7ab8c9c1a907da458f54b4b3410f846c4ae1934dc1873911d190c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
